import os

ANCHO = 1100
ALTO = 700
FPS = 60

VEL_REPARTIDOR = 4
VEL_PIZZA = 11
COOLDOWN_DISPARO = 180
INTERVALO_INVULNERABILIDAD = 1000
MAX_ENERGIA_DASH = 100
INTERVALO_APARICION_INICIAL = 2000
INTERVALO_APARICION_MINIMO = 800

# Configuración del gato
VEL_GATO_MULTIPLICADOR = 1.3
GATO_AMPLITUD = 5
GATO_FRECUENCIA = 0.15
GATO_ANCHO = 44
GATO_ALTO = 55
GATO_APARICION_INICIAL_SEG = 20
INTERVALO_APARICION_GATO = 4000

RUTA_BASE = os.path.dirname(__file__)
RUTA_IMAGENES = os.path.join(RUTA_BASE, "assets", "images")
RUTA_SONIDOS = os.path.join(RUTA_BASE, "assets", "sounds")

# Configuración de la caja de vida (power-up)
CAJA_VIDA_ANCHO = 48
CAJA_VIDA_ALTO = 48
CAJA_VIDA_INTERVALO_MIN = 15000
CAJA_VIDA_INTERVALO_MAX = 20000
CAJA_VIDA_TIEMPO_VIDA = 6000
CAJA_VIDA_MAX_VIDAS = 5

VOL_DISPARO = 0.4
VOL_GOLPE = 0.6
VOL_VIDA = 0.8
VOL_MUSICA = 0.5
